engines:
  csslint:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "codesize,controversial,design,unusedcode"

ratings:
  paths:
    - src/**
    - "**.php"

exclude_paths:
  - vendor/**/*
  - .git/**/*
  - composer.*
